version: '3.9'

### NETWORKS ###
networks:
  web:
    name: web
    driver: bridge
    external: false
    attachable: true

  database:
    name: database
    driver: bridge
    external: false
    attachable: true

services:

  postgresql:
    container_name: postgresql
    image: postgres
    ports:
      - "5423:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: apioficina
    networks:
      - web
      - database

  ca-api:
    image: ca_api-dev
    container_name: cap-api-dev
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8600:8600"
    environment:
      - SERVER_PORT${SERVER_PORT}
      - DATABASE_URL${DATABASE_URL}
      - DATABASE_USERNAME${DATABASE_USERNAME}
      - DATABASE_PASSWORD${DATABASE_PASSWORD}
      - MINIO_ENDPOINT${MINIO_ENDPOINT}
      - MINIO_PORT${MINIO_PORT}
      - MINIO_ACCESS_KEY${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY${MINIO_SECRET_KEY}
      - MINIO_SECURE${MINIO_SECURE}
      - MINIO_BUCKET_NAME${MINIO_BUCKET_NAME}
      - TZ=America/Sao_Paulo
    labels:
      # Traefik Config
      - "traefik.enable=true"
      - "traefik.http.routers.ca-api-dev.rule=Host(`ca-api-dev.app.pb.utfpr.edu.br`)"
      - "traefik.http.routers.ca-api-dev.tls.certresolver=letsencrypt"
      - "traefik.http.routers.ca-api-dev.entrypoints=websecure"
    restart: unless-stopped
    depends_on:
      - postgresql
    networks:
      - web
      - database
